default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kazan_uchi_development

test:
  <<: *default
  database: kazan_uchi_test

production:
  <<: *default
  database: kazan_uchi_production
